FROM node:18 AS build

WORKDIR /app

COPY workChronosFRONT/package.json workChronosFRONT/package-lock.json ./

RUN npm install

COPY workChronosFRONT/ ./

RUN npm run build --prod

FROM nginx:alpine

COPY --from=build /app/dist/workchronosFRONT /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
