services:
  db:
    image: postgres:14
    container_name: workChronosDB
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: chronos
      POSTGRES_PASSWORD: chronos
      POSTGRES_DB: workChronosDB
    volumes:
      - ./data/workChronosDB:/var/lib/postgresql/data